### ISSUE TITLE
Question / Answer Feature Tracking issue

### ISSUE THREAD

**Issue by FoseFx** [helpwave/rest-api#25]
* [ ] Add Models #17 
 * [ ] Add CRUD Routes for Questions and their Answers
   * [ ] Create Route
   * [ ] Get Route
   * [ ] (Get all Route?)
   * [ ] Update Route
   * [ ] Delete Route
 * [ ] Add Question <-> Emergency Interaction
   * [ ] Update Models
   * [ ] Answered Route
