### ISSUE TITLE
Auth Tracking Issue

### ISSUE THREAD

**Issue by FoseFx** [helpwave/rest-api#94]
Authentication and Authorization needs to be implemented as discussed [internally](https://wiki.helpwave.de/e/de/auth).

## Authentication
- [ ] Add models for users and organizations
- [ ] Login Route (Issue Access Token)
- [ ] Refresh Access-Token Route
- [ ] Implement Authorization Middleware

## Authorization
- [ ] Modify models of all ownable entities to reflect the org their owned by
- [ ] Add Authorization Middleware or function
